const ANSWER_STATUS = {
  DRAFT: "DRAFT",
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
  MANUAL_UPDATED: "MANUAL_UPDATED",
  MISSING_DATA: "MISSING_DATA",
};

const PROJECT_STATUS = {
  READY: "READY",
  CREATING: "CREATING",
  UPDATING: "UPDATING",
  OUTDATED: "OUTDATED",
};

const REQUEST_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};

module.exports = {
  ANSWER_STATUS,
  PROJECT_STATUS,
  REQUEST_STATUS,
};
